In [ ]:
import numpy as np

Nesting within the arrays are referrred as dimension in Numpy, nd array contains
n level of nesting.
A simple value here are known as scaler, 1d array are called as vectors, 2d arrays are the matrix and other dimensions after the 2d arrays are Images.
Numpy Arrays are designed to do numerical calculations.

It is around 50 times more faster than the Python List Data Structure.

Numpy are most optimized to do calculation without doing computation with iteration on every element, Any calculation done on the arrays in numpy are called as vectorization.

All the element within the array in numpy are of same data type, so we call them homogenous array

In [ ]:
# Example of vectorization on numpy arrays
numbers = np.array([10, 20, 30, 40])
result = numbers + 10
print(result)

[20 30 40 50]


# Creation

In [ ]:
# Properties of array object
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
#---------------------------------------
# Four main properties of the array
print(arr.size)  # length of the array
print(arr.ndim)  # dimension of the array
print(arr.shape) # rows and column return
print(arr.dtype) # data type of the array

6
2
(2, 3)
int64
[10.5 20.5 30. ]


In [ ]:
# Now there are some different ways to make the arrays in numpy
np.zeros() # Create an array of zeros
#----------------------------------
arr = np.zeros(5)
arr = np.zeros((3,4)) # tuple is passed as argument with the row and column

np.ones() # Create an array of ones
#-------------------------------------
arr = np.ones(5)
arr = np.ones((2, 3))

# np.full(shape, value)
arr = np.full((3, 4), 7)

#np.arange() # Create an array with a range of elements
np.arange(2, 10, 2) #(start, end, skip)
np.arange(10, 0, -2) # decrement

# np.linspace(start, stop, number_of_values)
np.linspace(0, 100, 5) # Create an array with a specified number of elements

np.random.rand(2,3) # Create an array with random values
np.random.randint(1, 100, (3, 4))

# Indexing

In [ ]:
# Indexing
arr = arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0,1])
print(arr[1,4])

2
10


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0,1,2])

6


In [ ]:
# Negative Indexing
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,-1])
print(arr[-1,-1])

10
10


# Slicing

In [ ]:
# Slicing Arrays
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5]) # slicing from index 1 to index 4
print(arr[1:]) # slicing from 1 to end
print(arr[:4]) # slicing from start to 3
print(arr[-3:-1]) #slicing from the 3rd index from end to second last index from the end

[2 3 4 5]
[2 3 4 5 6 7]
[1 2 3 4]
[5 6]


In [ ]:
# Slicing with skips
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [ ]:
# Slicing 2D arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[1:4,1])
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0:4,1])

[7 8 9]
[7]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
a2 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
# Slicing in arrays
print(a2[:,0])
print(a2[0,:])
print(a2[1:,1:3])
print(a2[::2,::3])
print(a2[1,::2])
print(a2[0:2,1:])

[1 4 7]
[1 2 3]
[[5 6]
 [8 9]]
[[1]
 [7]]
[4 6]
[[2 3]
 [5 6]]


# Reshaping

In [ ]:
#reshaping the vector into a matrix
arr = np.arange(10,20,1)
arr.size
arr.reshape((5,2))

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [ ]:
arr = np.linspace(10,20,10)
arr

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [ ]:
arr = np.arange(16).reshape(2,-1) # fixed the size of row to four and telling column is unfixed
print(arr)
print("")
arr2 = np.arange(16).reshape(-1,4) # here column is fixed to 4 but rows are unfixed
print(arr2)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


# Iterating

In [ ]:
# Iteration on 1D array
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

In [ ]:
# Iteration on 2D Array
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
# If we iterate on a n-D array it will go through n-1th dimension one by one.
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
# Iterating Arrays Using nditer()
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# iterate on the slice of the original array
for x in np.nditer(arr[:, ::2]):
  print(x)

In [ ]:
arr = np.array([1, 2, 3])

for x in np.ndenumerate(arr):
  print(x)

((0,), np.int64(1))
((1,), np.int64(2))
((2,), np.int64(3))


# Joining

In [ ]:
# Joining 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
# Joining 2D arrays along rows (axis=1)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Joining 2D arrays along columns (axis=0)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Stacking
#### Stacking means combining two or more arrays together along a particular axis.

np.vstack() → vertical stacking

np.hstack() → horizontal stacking

np.stack() → stacking along a new axis

In [ ]:
# np.vstack() — Vertical stacking
# Arrays are placed one below another.
a = np.array([[[1, 2, 3]]])
b = np.array([[[4, 5, 6]]])
result = np.vstack((a, b))

print(result)
# So vstack increases the number of rows.

[[[1 2 3]]

 [[4 5 6]]]


In [ ]:
# np.hstack() — Horizontal stacking
# Arrays are placed side by side.
a = np.array([[[[1, 2, 3]]]])
b = np.array([[[[4, 5, 6]]]])

result = np.hstack((a, b))

print(result)

[[[[1 2 3]]

  [[4 5 6]]]]


In [ ]:
# np.stack()
# axios = 0 (row) -- It combines arrays by creating a new axis.
# It looks similar to vstack, but internally the important difference is that stack() creates a new dimension.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=0)

print(arr)

#axis controls where the new dimension goes

[[1 2 3]
 [4 5 6]]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)


[1 2 3 4 5 6]


In [ ]:
a = np.arange(1,11).reshape(2,5)
b = np.arange(10,20).reshape(2,5)
print(a)
print(b)
np.hstack((a,b))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[10 11 12 13 14]
 [15 16 17 18 19]]


array([[ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 15, 16, 17, 18, 19]])

In [ ]:
a = a.reshape(5,2)
b = b.reshape(5,2)
print(a)
print(b)
np.vstack((a,b))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

# Spliting


In [ ]:
arr = np.arange(10,30).reshape(4,-1)
print(type(arr))

# after splitting it is creating list data structure from numpy array.
new_arr = np.split(arr,4)
print(type(new_arr))

<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
np.array_split(arr,4)

[array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29]])]

# # hsplit() and vsplit()

In [ ]:
# Vertical Splitting -- Cutting the Column horizontally
arr = np.arange(10,30).reshape(4,-1)
print(arr)
print("")

splited_arr = np.vsplit(arr,2) # only split equally else it would return an error
print(splited_arr)
print("")
print(type(splited_arr))

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

[array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]]), array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])]

<class 'list'>


In [ ]:
# Horizontal Splitting -- Cutting the Rows Vertically
arr = np.arange(10,30).reshape(4,-1)
print(arr)
print("")

# here 5 columns are present in arr, so you can't use hsplit and split, they will return error as they only
# split equally so here we will split them through array_split()
splited_arr = np.array_split(arr,3, axis=1) # only split equally else it would return an error
print(splited_arr)
print(type(splited_arr[0]))

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

[array([[10, 11],
       [15, 16],
       [20, 21],
       [25, 26]]), array([[12, 13],
       [17, 18],
       [22, 23],
       [27, 28]]), array([[14],
       [19],
       [24],
       [29]])]
<class 'numpy.ndarray'>


# Searching
#### search an array for a certain value, and return the indexes that get a match.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print((x[0]))


[3 5 6]


In [ ]:
arr = np.array([10, 14, 93, 41, 8, 7])

x = np.where(arr%2 == 1)

print(x)

(array([2, 3, 5]),)


# Search
#### searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.
#### The searchsorted() method is assumed to be used on sorted arrays.

In [ ]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x) # The number 7 should be inserted on index 1 to remain the sort order.

# Now find the index where 7 should be inserted starting from the right side.
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

# For Multiple Values -- Find the index where 2,4 and 6 should be inserted
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

1
2
<class 'numpy.ndarray'>


# Sorting Arrays

In [ ]:
arr = np.array([3, 2, 0, 1])

# Create the copy of the array leaving original array unchanged
print(np.sort(arr))

arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[0 1 2 3]
[[2 3 4]
 [0 1 5]]


In [ ]:
np.argsort(arr) # index of the array will gonna be the output

array([0, 1, 2, 3])

In [ ]:
# descending sorting
-1*np.sort(-arr)

array([44, 43, 42, 41])

# Filtering Arrays

In [ ]:
# Creating a new array after filtering the original array with the boolean index list. [True, False, True, False, False]

arr = np.array([41, 42, 43, 44])
boolean_index = []

boolean_index = arr > 42

newarr = arr[boolean_index]

print(boolean_index)
print(newarr)

# filter an array that will return only even elements from original array

[False False  True  True]
[43 44]


## Masking
##### We can simply call it creating boolean index for filtering the array based on the condition

In [ ]:
ml = np.arange(12).reshape(3,4)
ml

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
mask = ml < 6
mask

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [ ]:
np.sum(mask) # this way we can count the element that match our condition passed in the array

np.int64(6)

In [ ]:
ml[mask]

array([0, 1, 2, 3, 4, 5])

In [ ]:
print(ml[ml % 2 == 0])

# Multiple Conditions
arr = np.array([5, 10, 15, 20, 30, 40, 50])

result = arr[(arr > 10) & (arr < 40)]
print(result)

[ 0  2  4  6  8 10]
[15 20 30]


## Vectorization
##### Vectorization means performing an operation on an entire array at once


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
add_arr = arr + 2
print(add_arr)

multiply_arr = arr * 2
print(multiply_arr)

[12 22 32 42 52]
[ 20  40  60  80 100]


In [ ]:
import math
import numpy as np

arr = [10, 20, 30, 40, 50]
vec_log = np.vectorize(math.log)
result = vec_log(arr) # used specially for the customized function
print(result)

[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]


In [ ]:
def custom_loss(a,b):
  return (a**2+b**2)**0.5

vec_custom_loss = np.vectorize(custom_loss)
x = np.arange(10)
y = np.arange(10,20)
vec_custom_loss(x,y)

array([10.        , 11.04536102, 12.16552506, 13.34166406, 14.56021978,
       15.8113883 , 17.08800749, 18.38477631, 19.6977156 , 21.02379604])